### PR TITLE
cluster.discoverConnection now uses ConnectionWatcher on the client a…

### PR DESCRIPTION
**Pull request by patrickleet**
…s well as the server. Added a server side method to pick endpoint from client, which is used by ConnectionWatcher when not on the server.

Addresses #27

### CODE REVIEW

**Comment by patrickleet** [comment]
All tests pass when run locally.

**Comment by patrickleet** [comment]
I'm not sure the best practices for doing adding a Meteor.Method to a package. If you have a better way let me know.

**Comment by patrickleet** [comment]
This works locally but running into some issues when deployed.

On my production environment, pickEndpoint returns an IP Address instead of a domain name. The IP address is http, not https. 

Guessing this has something to do with balancer, and selecting the balancer URL instead of the endpoint when available.

**Comment by patrickleet** [comment]
@arunoda Please advise on usage of balancer in this situation. 

I'm concerned with the scenario where a balancer is not provided for the endpoint, as then it would return the IP Address?

**Comment by arunoda** [comment]
ConnectionWatcher is server side only. It wraps a DDP connection. Once disconnected, it'll try to connect to a different service instance.

I'll response #27 regarding the issue.

**Pull request closed without merging**
